### ISSUE TITLE
Improve error message from partitioning when there are more processes than atoms

### ISSUE THREAD

**Issue by Euicheol-Shin** [OrderN/CONQUEST-release#106]
Many thanks to the Conquest developer team for their hard work and open source.
Recently, after installing the code, I keep running into an error while doing exercises for Silicon.

Each node I use has 12 cores. When using the silicon example with 12 cores of a single node, the following error message appears,

 Error in process    1
 sfc_partitions_module: too few occupied partitions for number of processors         8        12

If one node uses 8 cores, it runs successfully. Since it is still in the early stages of public disclosure, there are no detailed forums or other discussions about the content, so I leave a problem here.

Thank you,
Euicheol

**Comment by davidbowler** [comment]
Hi Euicheol.  Thanks for your interest in Conquest.

We require at least one atom per process to run Conquest, so with the simple 8 atom silicon cell, you cannot run on more than 8 processes (or cores/processors if you prefer).

We should make the error clearer - I will change the name of the issue to reflect this.

I hope that helps.

Dave

**Comment by tsuyoshi38** [comment]
Thank you very much for your feedback. 
How many atoms do you have in your system ?   
If it only includes 8 atoms, CONQUEST now assumes that each MPI process should include at least one atom, for parallel efficiency. Thus, the code runs with 8 processes, but not with 12 processes. 

For the forum, we have a mailing list. (but, I forgot its name..)

**Comment by Euicheol-Shin** [comment]
> Hi Euicheol. Thanks for your interest in Conquest.
> 
> We require at least one atom per process to run Conquest, so with the simple 8 atom silicon cell, you cannot run on more than 8 processes (or cores/processors if you prefer).
> 
> We should make the error clearer - I will change the name of the issue to reflect this.
> 
> I hope that helps.
> 
> Dave

Thanks for the very quick feedback.

I have a clear understanding of the problem. Thank you for your hard work.

Euicheol

**Comment by Euicheol-Shin** [comment]
> Thank you very much for your feedback. How many atoms do you have in your system ? If it only includes 8 atoms, CONQUEST now assumes that each MPI process should include at least one atom, for parallel efficiency. Thus, the code runs with 8 processes, but not with 12 processes.
> 
> For the forum, we have a mailing list. (but, I forgot its name..)

Thank you, Tsuyoshiさん

If you can give the mailing list of the forum, it would be more helpful.

Euicheol
