### ISSUE TITLE
ASE always need "Kpoints in fractional coordinates" to be print in Conquest output

### ISSUE THREAD

**Issue by lionelalexandre** [OrderN/CONQUEST-release#116]
When using ASE for band structure calculation and plot, we always need the "Kpoints in fractional coordinates" to be printed in the output. This is done when asking for "Diag.KpointLines" and "Diag.MPMesh" mesh but not when using "Diag.Kpoints" block.

**Comment by davidbowler** [comment]
Fixed with #117
