### ISSUE TITLE
Problem in setting spin-dependent atomic charge density

### ISSUE THREAD

**Issue by tsuyoshi38** [OrderN/CONQUEST-release#127]
For multi-element systems, even when we set different electron numbers for spin up and down electrons of some elements, CONQUEST does not set the initial density is not set properly.  
It is because the flag `flag_InitialAtomicSpin` in `initial_read_module.f90` is not set properly for multi-element systems, I think.  It is now set in the do-loop of species for every species, thus can be overwritten. 
We will correct it soon, but for now, the problem may be solved if we set the element which needs to be spin polarized as the last element.

**Comment by tsuyoshi38** [comment]
I am not completely sure, but I think..  even with the correction mentioned above, the present version of CONQUEST seems to have a problem in setting the initial spin-dependent atomic charge density.   
 In addition to this, even after we get the spin-polarized SCF density, the density made from K-matrix is found to be not spin polarized again.  It is strange. I will check more.  (Kmatrix should be spin dependent, of course.)
(I am now working with "f_rework_output".)

**Comment by lionelalexandre** [comment]
I have found a similar issue in the merged f-rework-output(-ase). Initialisation of spin-up and spin-dn can be fixed.
But still problems in running spin-pol calculation. Note that this issue doesn't exist in f-rework-output-ase which is based on a older version of  f-rework-output. This will help to find the problem which should be located in a few commits. I m working on.

**Comment by davidbowler** [comment]
Should be fixed by #133 (merge of f-rework-output)

**Comment by davidbowler** [comment]
Fixed by #133
