### ISSUE TITLE
Installation: deps.obj.inc missing

### ISSUE THREAD

**Issue by VictorEijkhout** [OrderN/CONQUEST-release#157]
The `deps.obj` file includes `deps.obj.inc` but I'm not finding it in the repository, nor does the readthedocs seem to mention it.

How do I find/make this file?

**Comment by davidbowler** [comment]
The file is generated automatically during the make process (you can see the lines in Makefile if you're interested) so you don't need to do anything!

If you find that it is not created automatically, please start a Discussion and we'll try to help
