### ISSUE TITLE
Post-processing issue for band density: integration value

### ISSUE THREAD

**Issue by JianboLin** [OrderN/CONQUEST-release#173]
When we integrate the value from the cube file of band density and multiply with grid volume, it is expected to result 1.
But, I find it is not always 1. 
This problem was detected in SiGe system 1000 atoms. Since this SiGe system is large, I prepared with small systems of 
1) 2 Fe atoms BCC, hamman DZP PBE
2) 8 Si atoms diamond, hamman DZP PBE
3) 8 Si atoms diamond, hamman DZP LDA

All the total charge densities (chden.cube) give correct results of electron number.
In the case of Fe, integrations of band density give correct values near to 1. However, in two Si cases, integrations of band density give strange values far from 1.
Please find the files of .txt including these results. There are also input files for these three small systems.
I hope you have your own code to do the integration. If not, please use the cube_tool of python code in analysis_tool, with cmd,
python cube_tools_v2.0_original.py -i  filename.cube

I can not upload cube files, only 25MB allowed.
[PostProcess_chden_bandden_check.tar.gz](https://github.com/OrderN/CONQUEST-release/files/11169931/PostProcess_chden_bandden_check.tar.gz)

**Comment by davidbowler** [comment]
I think that this will be addressed in branch bugfix-post-process-charge

**Comment by JianboLin** [comment]
Thank you very much. I tested using the same examples with this branch of bugfix-post-process-charge. The results of total charge density keep the previous value. The results of band density show no significant improvement with present version.

**Comment by davidbowler** [comment]
I just ran a test on the `Si8_diamond_DZP_hamman_LDA` case, and the integral is 1.000 in every case.  Did you rebuild the post-processing tool? (something like `cd tools/PostProcessing; make`).  Once you have rebuilt it, when it runs you should get a line like this in the output:

`Git Branch: bugfix-post-process-charge; tag, hash: v1.0.5-pre-289-g8fd5a861`

Please check the Git hash (it should be 8fd5a861).

**Comment by JianboLin** [comment]
Thank you for your comment! I rebuilt PostProcess and recalculated the examples from begining. 
Now all the three cases give 1.000 for the integral value.

**Comment by davidbowler** [comment]
That's excellent! Could you approve the pull request, please? (Or maybe @tsuyoshi38 or @ayakon could approve it)

**Comment by davidbowler** [comment]
Fixed by #181
