### ISSUE TITLE
Add input for tests

### ISSUE THREAD

**Issue by tkoskela** [OrderN/CONQUEST-release#177]
First step in populating the test suite. Collect input files for whole-code (integration) tests in [f-develop-test-suite](https://github.com/OrderN/CONQUEST-release/tree/f-develop-test-suite)

**Comment by davidbowler** [comment]
Something seems to be broken with the python version here. @tkoskela Can you take a look please?

**Comment by davidbowler** [comment]
Actually I've now (at a very basic level) fixed this; syntax in Makefile.yml (python version needed quotes); adding numpy to pip install; adjusting the decimals to four.

I think that it would be better if we could have different numbers of decimal points for each test, if that's easy to add (stress should be fewer decimals than energy, for instance).  I've shifted to four decimals for now.

**Comment by davidbowler** [comment]
This is now done, and we have (initial) working tests and CI.
