### ISSUE TITLE
Choose testing framework

### ISSUE THREAD

**Issue by tkoskela** [OrderN/CONQUEST-release#187]
For the medium term, we need to select a testing framework to run tests with. Popular options include
- [pFUnit](https://github.com/Goddard-Fortran-Ecosystem/pFUnit) a parallel Fortran testing framework developed by NASA Goddard. 
    - We've used this previously in https://github.com/UCL/SparseDemand
- [test-drive](https://github.com/fortran-lang/test-drive) a lightweight testing framework advocated by [fortran-lang](https://fpm.fortran-lang.org/en/tutorial/dependencies.html#adding-a-testing-framework)

**Comment by tkoskela** [comment]
My opinion is that pFUnit makes more sense because of its stability. test-drive looks interesting but immature at this point.

pros:
- Actively developed
- Support for MPI tests
- Can integrate with [ctest](https://github.com/Goddard-Fortran-Ecosystem/pFUnit/blob/main/include/add_pfunit_ctest.cmake)
- We've used it in [previous projects](https://github.com/UCL/SparseDemand/tree/master/test)
cons:
- It's a bit heavy -- probably including it as a git submodule makes most sense
- Uses metaprogramming -- compiling tests gets more complicated 
- Documentation is not great -- but there are some examples in another repo + tutorials on the internet,

**Comment by tkoskela** [comment]
Decided to postpone unit tests and focus on end-to-end testing to begin with.

**Comment by davidbowler** [comment]
I wonder if we should actually close this, as we're unlikely to implement unit testing.

**Comment by davidbowler** [comment]
Closing this for now since our tests are end-to-end at the moment.
