### ISSUE TITLE
Unit of Efermi in Conquest_out of PostProcessing

### ISSUE THREAD

**Issue by ayakon** [OrderN/CONQUEST-release#209]
In Conquest_out of PostProcessing, Fermi level is shown in Hartree unit
(ex., "Fermi level:     -0.17719 Ha").
while the STM energy region is given in eV unit
(ex., "Including bands between  -4.822 and  -4.722 eV", where -4.822 eV = -0.17719 Ha.),
so it is not easy to compare with Fermi level.

It might be good that we show Fermi level both in Hartree and eV units,
somehow like "Fermi level:     -0.17719 Ha  =  -4.822 eV".

**Comment by davidbowler** [comment]
Closed by #217
