### ISSUE TITLE
Hartree stress wrong for non-SCF calculations

### ISSUE THREAD

**Issue by davidbowler** [OrderN/CONQUEST-release#214]
The Hartree stress found with non-SCF calculations is wrong, I think (it is often several hundred Ha while for the equivalent SCF calculation it is around 1Ha).  More investigation required.

**Comment by davidbowler** [comment]
The problem is simply that this routine was not written to account for the neutral atom potential! Background physics will be needed followed by changes to evaluate Hartree stress on appropriate charge density.

**Comment by lionelalexandre** [comment]
Does this can also explain the problem with geometry optimisation with nonSCF?

**Comment by davidbowler** [comment]
Quite possibly: I have found a simple error for the nonSCF geometry optimisation (more on this soon) but possibly there is a problem with non-SCF forces as well…

**Comment by davidbowler** [comment]
Further information on the forces (which I will also put in a separate issue, but forces and stress are intimately linked) is that the presence of PCC seems to be the problem for non-SCF forces (atoms without PCC have perfect forces).  I'm not sure why yet!

**Comment by davidbowler** [comment]
Part of the problem here has been fixed by #218 (the force error was also present in the stress) so non-neutral-atom calculations are now correct.  But the neutral atom still needs a reformulation to find the stress correctly.

**Comment by davidbowler** [comment]
This is now fixed by #229
