### ISSUE TITLE
Bug (?) in if-statements before calling dump_pos_and_matrices

### ISSUE THREAD

**Issue by tsuyoshi38** [OrderN/CONQUEST-release#236]
After I updated the MacOS, I encountered a problem in the following part with the option (-O3).
       if (n_dumpL>0 .and. mod (n_iter, n_dumpL) == 0) then
           call dump_pos_and_matrices(index=unit_DM_save)
       endif

The problem seems to come from the 2nd one when n_dumpL=0.
I thought it is not used since we also checked n_dumpL. But, it is probably safer to change it to 
       if (n_dumpL>0) then
          if(mod (n_iter, n_dumpL) == 0)  call dump_pos_and_matrices(index=unit_DM_save)
       endif

**Comment by davidbowler** [comment]
Fixed in #237
