### ISSUE TITLE
Output frequency for xsf and xyz trajectories

### ISSUE THREAD

**Issue by AugustinLu** [OrderN/CONQUEST-release#255]
At present, when `AtomMove.WriteXSF = .TRUE.` and/or `AtomMove.WriteExtXYZ = .TRUE.`, trajectories in XSF and/or extXYZ format are written at each time step.

For long molecular dynamics simulations, these trajectory files can become huge, and not all frames are necessary.

Is it possible to add a keyword to control the frequency at which these files are written? Some possibilities could be:

1. Using `AtomMove.OutputFreq` to control all of them together. 
2. Defining `AtomMove.XsfFreq` and `AtomMove.XyzFreq` for control them separately. 

Thank you very much.

**Comment by tsuyoshi38** [comment]
Personally, I prefer to have all of these keywords and the default values of `AtomMove.XsfFreq` and `AtomMove.XyzFreq` are set by `AtomMove.OutputFreq`.

**Comment by AugustinLu** [comment]
An implementation of the two additional keywords is proposed in the forked repository: [4fa7fcf](https://github.com/AugustinLu/CONQUEST-release/commit/4fa7fcfc82bf4d275bbcba2eb16bb3d027fd775f)

- If no value is provided, the default value for `AtomMove.XsfFreq` and `AtomMove.XyzFreq` are equal to `AtomMove.OutputFreq`
- **trajectory.xsf** is written every  `AtomMove.XsfFreq` steps and **trajectory.xyz** is written every  `AtomMove.XyzFreq` steps, if the corresponding flags are set to `.TRUE.`.

**Comment by davidbowler** [comment]
This looks like a very sensible solution: thank you.

**Comment by davidbowler** [comment]
Closed by #258
