### ISSUE TITLE
Possibility of stopping properly MD whereas the number of steps is not reached

### ISSUE THREAD

**Issue by lionelalexandre** [OrderN/CONQUEST-release#311]
it would be nice to have the possibility of stopping MD run on-the-fly by using an flag in Conquest_input or file (like STOPCAR in VASP).

**Comment by AugustinLu** [comment]
Creating a file named `CQ.stop` should stop the simulation. Is it what you are looking for? 

https://github.com/OrderN/CONQUEST-release/blob/6bf8f4a8c20fd4fa8f1c7baeb8a6b1f23a6d2408/src/io_module.f90#L3532

**Comment by lionelalexandre** [comment]
Thank you very much, I didn't know...
