### ISSUE TITLE
Changing the order of atoms in velocity.dat

### ISSUE THREAD

**Issue by tsuyoshi38** [OrderN/CONQUEST-release#312]
It is sometimes useful if we can set the initial velocity of atoms manually to start MD simulations.
In principle, we can do it by reading these values from the file `velocity.dat`. 
However, the order of atoms in this file are weird and different from that in coordinate file, because it follows the old-CONQUEST format (partition labeling).
We (Lionel and I) believe it should be changed and I would like to do it soon.

Note that `md.checkpoints`, which is used in restarting MD ,also has the same problem. 
But, as many users may have already  stored the data in this format, I wonder we should change it later. 
(Probably before a major version up.)

**Comment by davidbowler** [comment]
Closed by #351
