### ISSUE TITLE
Save stress tensor in xyz trajectory file.

### ISSUE THREAD

**Issue by AugustinLu** [OrderN/CONQUEST-release#378]
At present, the `trajectory.xyz` file written during molecular dynamics simulations contains the positions, forces and energies but no information about the stress tensor.

It would be useful to have the stress tensor written in the header as it could be read by ASE and re-used for further postprocessing.

**Comment by davidbowler** [comment]
This is a good idea but I didn't know that stress could be written to xyz files.  Is there a specification document?

**Comment by JianboLin** [comment]
For each geometry, in the second comment line, the information of stress can be appended with an string, which is convenient for further analysis with ASE or others.

**Comment by AugustinLu** [comment]
As @JianboLin wrote, stress, as any property, scalar or vector, can be stored in the second line of what would be the comment line of xyz files. In the extended XYZ format, the comment line is considered as a series of key/value pairs.

In the proposed implementation, the stress tensor would be saved as the elements of the 3x3 matrix in the format specified in ASE:
https://wiki.fysik.dtu.dk/ase/ase/io/formatoptions.html#extxyz
If the property "stress" is present , it will be read by ASE.

Lattice="7.976251045 -0.066073409 0.094473673 0.0 8.1188244 0.053663813 -0.0 -0.0 10.10463222" Properties=species:S:1:pos:R:3:forces:R:3 **stress="0.006635310902671738 -0.0021648924063491113 0.008182624705542077 -0.0021648924063491113 -0.0008392270755571369 0.003454257120064949 0.008182624705542077 0.003454257120064949 0.011619180905726022"** free_energy=-227.33788785 energy=-227.34438726 pbc="T T T"
