### ISSUE TITLE
Error message with "make clean"

### ISSUE THREAD

**Issue by ayakon** [OrderN/CONQUEST-release#44]
When we "make clean" in the src directory, an error message appears,

***
(cd utilities; make -k clean)
make[1]: Entering directory `/home/user/CONQUEST-release/src/utilities'
make[1]: *** No rule to make target `clean'.
make[1]: Leaving directory `/home/user/CONQUEST-release/src/utilities'
make: *** [clean] Error 2
***

This error relates to "utilities" and causes no problem for the main Conquest code.
This error will be fixed in future.

**Comment by davidbowler** [comment]
Closed with #48
