### ISSUE TITLE
Small change when setting DM.SolutionMethod     

### ISSUE THREAD

**Issue by tsuyoshi38** [OrderN/CONQUEST-release#47]
If you would set 
 DM.SolutionMethod  diag
by mistake, your calculations would be O(N) mode, not diagonalisation, though the default option of DM.SolutionMethod is "diagon".

This is because the corresponding part (initial_read_module.f90) is

   ! Solution method - O(N) or diagonalisation ?
   method = fdf_string(6,'DM.SolutionMethod','diagon')
   if(leqi(method,'diagon')) then
      flag_diagonalisation = .true.
      flag_check_Diag = .true.
   else
      flag_diagonalisation = .false.
      flag_check_Diag = .false.
   end if

Thus, I think we should change this part as following, 

   ! Solution method - O(N) or diagonalisation ?
   method = fdf_string(6,'DM.SolutionMethod','diagon')
   if(leqi(method,’ordern')) then
      flag_diagonalisation = .false.
      flag_check_Diag = .false.
   else
      flag_diagonalisation = .true.
      flag_check_Diag = .true.
   end if

What do you think ?  
(Can I add "area:input" ?  
And..   This is not a bug, to be strict.)

**Comment by davidbowler** [comment]
I agree: this is very reasonable.
