### ISSUE TITLE
Cell optimisation with constrained ratios doesn't work

### ISSUE THREAD

**Issue by davidbowler** [OrderN/CONQUEST-release#50]
The constrained ratio cell optimisation code (e.g. constrain b/a ratio) doesn't work.

The code needs updating so that b/a is treated differently to a/b (etc)

**Comment by jackbaker1001** [comment]
I noticed today that the constraints only work for AtomMove.OptCellMethod 1. It would be useful if these were available for the simultaneous optimisation (AtomMove.OptCellMethod 3). Would this be easy to do @Paraquat ?

**Comment by davidbowler** [comment]
It looks to me like it should be easy enough to implement, though it should be part of a separate issue and pull request ideally.

**Comment by davidbowler** [comment]
Closed with #51
