### ISSUE TITLE
ScaLAPACK pzhegvx evec warning ... INFO= 2

### ISSUE THREAD

**Issue by negf** [OrderN/CONQUEST-release#61]
only a minor cosmetic point but if many k-points are used during diagonalization the output can get spammed with many "ScaLAPACK pzhegvx evec warning ... INFO= 2" warnings in each SCF step, maybe one could just give a single accumulated warning at the end of the SCF step instead.

**Comment by davidbowler** [comment]
Yes, this is a reasonable suggestion - thank you.

**Comment by davidbowler** [comment]
This has been addressed in the f-rework-output branch which will be merged into develop very soon.

**Comment by davidbowler** [comment]
Closed by #133
