### ISSUE TITLE
Small bug: strange output of electron number when loading DM

### ISSUE THREAD

**Issue by tsuyoshi38** [OrderN/CONQUEST-release#62]
I have just notice that when we start a job by reading density matrix files
`General.LoadDM              T`
obtained by another job, we have a strange output for electron numbers.
Since the job is not the one during the MD, 
`AtomMove.RestartRun              F `
(and `SC.MakeInitialChargeFromK              T     # Default value`)

At present, with this setting, CQ first tries to prepare initial L matrix and calculate the charge density from this L matrix, which is not very good. Then, we sometimes observe a strange value in the electron numbers (probably when inverse S is not very accurate). Of course, this is a bug since we don't need initial L matrix when we read L matrix from the files, and the charge density will be made after reading L matrix.

Thus, the behavior of the code is correct, except the strange output for electron numbers.

The corresponding part will be around line 1894 in `initialization_module.f90`.

    if (.not. flag_diagonalisation .and. find_chdens .and. (start .or. start_L)) then
       call initial_L()
       call my_barrier()
       if (inode == ionode .and. iprint_init > 1) &
            write (io_lun, *) 'Got L  matrix'
       if (vary_mu) then
          ! This cannot be timed within the routine
          call start_timer(tmr_std_densitymat)
          call correct_electron_number
          call stop_timer(tmr_std_densitymat)
       end if
    end if

I will fix it soon.  (it may be better to remove the old variable `start_L` now.)

**Comment by davidbowler** [comment]
Fixed by #249 (the DM was being reset using `initial_L` which gave the wrong electron number)
