### ISSUE TITLE
Missing potential and input file in pseudo-and-pao for O

### ISSUE THREAD

**Issue by lionelalexandre** [OrderN/CONQUEST-release#66]
Oxygen atom potential and MakeIonFiles input are missing in the LDA and PBE directory. Maybe Dave have them somewhere.

**Comment by davidbowler** [comment]
Thank you for spotting this! The PBE and PBEsol files seem to be there, though as you say the LDA are missing.

**Comment by smujahed** [comment]
If I can jump on this bandwagon, there's no LDA for Ge.

**Comment by davidbowler** [comment]
Systematic check:  compared to PBE, LDA is missing

Co, Cs, Ge, La, Lu, Mn, Ni, O

Any others I've missed?

**Comment by davidbowler** [comment]
It turns out that the missing elements have no entries in PseudoDojo for LDA with the standard accuracy.  They do seem to exist with stringent accuracy.  

@lionelalexandre @smujahed please check that I've not missed any more; I'll then generate the files and issue (another) hot fix.

**Comment by lionelalexandre** [comment]
Considering the 6 firsts rows, the At atom is also missing for all the functional

**Comment by smujahed** [comment]
> It turns out that the missing elements have no entries in PseudoDojo for LDA with the standard accuracy. They do seem to exist with stringent accuracy.
> 
> @lionelalexandre @smujahed please check that I've not missed any more; I'll then generate the files and issue (another) hot fix.

@davidbowler I've just had a look. La and Lu definitely don't have LDA for standard accuracy. Co, Cs, Ge, Mn, Ni and O do seem to have standard accuracy potentials, but they don't have values for the tests (delta, delta1 and gbrv). I may be looking at a different version of ONCVPSP though. 

Just for reference, I am looking at them on www.pseudo-dojo.org/index.html with options:
- Type: NC SR ONCVPSP v0.3
- XC: LDA
- Accuracy: Standard
- Format: UPF

**Comment by davidbowler** [comment]
> Considering the 6 firsts rows, the At atom is also missing for all the functional

Yes - it seems to be unavailable (though I'm not sure how much interest there is in it!)

**Comment by davidbowler** [comment]
Thanks, @lionelalexandre I hadn't seen that v0.3 was available - v0.4 is not (and there's no clear explanation).

**Comment by smujahed** [comment]
I think I've made a mistake, my apologies! 

Inspecting the headers of the NC SR v0.4 LDA UPF files, files are marked as generated with v3.3.0 of ONCVPSP (at least for Si and As). Seems v0.3 UPFs are marked as using v3.2.3 of ONCVPSP... I'm very confused by the version convention on the PseudoDojo website.

**Comment by davidbowler** [comment]
It looks to me from what I can see that there are *no* potentials for La or Lu with LDA at either the standard or stringent levels.  I don't understand why this is (they are present for PBE and PBEsol).

**Comment by davidbowler** [comment]
Fixed by #69
