### ISSUE TITLE
Segmentation fault - invalid memory reference at pzhegvx call

### ISSUE THREAD

**Issue by lionelalexandre** [OrderN/CONQUEST-release#67]
I get a segmentation fault error message when trying to execute Conquest (develop branch)
on Silicon and other systems which seems to originate from pzhegvx of scalapack. I looked up 
to the arrays and dimensions of pzhegvx input variables, it seems to be ok; gfortran compiler has been used.

**Comment by davidbowler** [comment]
Can you supply input files please?

**Comment by lionelalexandre** [comment]
Attached the input files
[Si_test.zip](https://github.com/OrderN/CONQUEST-release/files/4932612/Si_test.zip)

**Comment by davidbowler** [comment]
OK - I have no problems running this with the version:

Git Branch: develop; tag, hash: v1.0.2-pre-30-g9f3c7e79

(which is the latest version).  Can you please set:

IO.Iprint 3
IO.WriteOutToFile F

and run the code, redirecting output to a file (e.g. using `mpirun -np 1 Conquest | tee output_crash`) and send me the output?  Please also tell me the version of Conquest, the compiler you're using, and which Scalapack version.

**Comment by lionelalexandre** [comment]
I do suspect as well that the problem is related to Scalapack (v2.1.0), although I have recompiled the library using the
same version of gfortran ; I get the same issue with an older version of Conquest. Attached 2 output files
from the current develop and the older versions. I'll continue to dig in... 
[Si_test.zip](https://github.com/OrderN/CONQUEST-release/files/4936728/Si_test.zip)

**Comment by lionelalexandre** [comment]
Just to let know that I've recompiled Scalapack and Conquest using gfortran/mpich (gcc7) and I get the same error.

**Comment by lionelalexandre** [comment]
I found that Con

**Comment by lionelalexandre** [comment]
The problem is solved by using the internal BLAS library of LAPACK compiled under the default name "refblas". Note that any attempt to execute Conquest compiled with the netlib BLAS libraries failed, leading to the "Segmentation fault" when pzhegvx is called.
