### ISSUE TITLE
possible memory leak in buildK (DiagModule.f90)

### ISSUE THREAD

**Issue by negf** [OrderN/CONQUEST-release#71]
In buildK (DiagModule.f90) recv_info is defined as derived data type Krecv_data, all but the recv_info(i)%ndimj(maxloc) component are individually deallocated before deallocating the parent recv_info, this missing deallocation caused a memory leak for me. 
I am not sure if this is the normal Fortran behavior or a problem with the compiler, eitherway as the other components of recv_info are already individually deallocated maybe we should also deallocate recv_info(i)%ndimj before deallocating the parent, just to be safe.

I am on master (commit f5075b9357fae5ac95fbd29560bd4bc360f3d212).

**Comment by davidbowler** [comment]
Thank you for finding this - `recv_info%ndimj` should certainly be deallocated.  Is it a serious memory leak (in which case we will make this a hot fix on master) or relatively small?

**Comment by negf** [comment]
I think not so serious, it may add up during longer MD runs, though.
--------------------------------------------------------------------------------------------------------
マリウス　ビュクル, Ph.D.

bI技gt合研究所
C能材料コンピュテ`ショナルデザイン研究センタ`　
305-8568 茨城hつくば市梅@ 1-1-1 つくば中央第2

TEL: 029-862-6947
FAX: 029-861-3171
E-mail: marius.buerkle@aist.go.jp


Marius Buerkle, Ph.D.

Research Center for Computational Design of Advanced Functional Materials, AIST

Central2, 1-1-1, Umezono, Tsukuba, 305-8568, Japan

TEL: 029-862-6947
FAX: 029-861-3171
E-mail: marius.buerkle@aist.go.jp

--------------------------------------------------------------------------------------------------------
________________________________

**Comment by davidbowler** [comment]
This should have been fixed by the branch bugfix-diag-memory-leak.  Could you please test it @negf ?

**Comment by negf** [comment]
Thanks for the quick fix, I think the memory leak is fixed with this patch.

--------------------------------------------------------------------------------------------------------
マリウス　ビュクル, Ph.D.

bI技gt合研究所
C能材料コンピュテ`ショナルデザイン研究センタ`　
305-8568 茨城hつくば市梅@ 1-1-1 つくば中央第2

TEL: 029-862-6947
FAX: 029-861-3171
E-mail: marius.buerkle@aist.go.jp


Marius Buerkle, Ph.D.

Research Center for Computational Design of Advanced Functional Materials, AIST

Central2, 1-1-1, Umezono, Tsukuba, 305-8568, Japan

TEL: 029-862-6947
FAX: 029-861-3171
E-mail: marius.buerkle@aist.go.jp

--------------------------------------------------------------------------------------------------------
________________________________

**Comment by davidbowler** [comment]
Fixed with #76
