### ISSUE TITLE
hybrid functionals

### ISSUE THREAD

**Issue by negf** [OrderN/CONQUEST-release#72]
I wonder what is the status of the implementation of hybrid functionals/ range separated functional. In the manual it states "If the code is compiled with LibXC, the full LibXC set of functionals is available" but this only applies to pure functionals, right? If a hybrid functional is selected it simply ignores the exact exchange contribution.

**Comment by davidbowler** [comment]
You are quite correct: we do have a preliminary implementation of exact exchange, but it's alpha version only.  I am not sure if a hybrid functional with LibXC would even run.  We will change the manual.
