### ISSUE TITLE
problem in conquest.bib

### ISSUE THREAD

**Issue by tsuyoshi38** [OrderN/CONQUEST-release#73]
Dr. Watanabe pointed out the problem in writing `conquest.bib`, since `write_bib` in `biblio_module.f90` from all MPI processes.  I also found that the file is sometimes broken.  He also pointed out that CONQUEST sometimes crashes due to this problem.   (It may depend on a system.)  
We can fix it simply by using (if (node == ionode))  in `write_bib`,  I think.

**Comment by davidbowler** [comment]
It can be fixed in `write_bib` or it could be made simpler by changing `compile_biblio` in `references.f90` to make the routine only run for `inode==ionode`.
