### ISSUE TITLE
problem during cell optimization

### ISSUE THREAD

**Issue by negf** [OrderN/CONQUEST-release#83]
Hi,

I try to optimize the atomic positions and unit cell. After some number of lbfgs steps it stops to calculate forces and to update the atomic positions and just calculates the total energy for the same structure over and over again. 
If I stop the calculation and copy the last updated geometry from coord_next.in to coord.in and restart the calculation it works again for several iterations and then the same problem occurs. 

I think I am on the latest release version.

I attached the Conquest input  I used and output  I got.

Marius
[cell_opt.tar.gz](https://github.com/OrderN/CONQUEST-release/files/5737651/cell_opt.tar.gz)

**Comment by davidbowler** [comment]
Please try this now with the new cell optimisation routines (though these still only use CG for now).  I'm closing for now.
