### ISSUE TITLE
Incorrect array indices lead to segmentation faults with the Cray Fortran compiler

### ISSUE THREAD

**Issue by welucas2** [OrderN/CONQUEST-release#85]
Building and running CONQUEST on ARCHER2 with the Cray Fortran 10.0.4 compiler leads to segmentation faults early in the run. gdb4hpc traces the stack to `get_nonSC_correction_force()` in force_module.f90. Further investigation leads to the culprit being bad array indices `j` and `j+1` in `atomic_density_table(the_species)%table` at lines 3673 to 3676. A value of `j = -2147483647` indicates an overflow. Following the calculation back shows the problem to be in the calculation of `rsq`. The same problem occurs later in the subroutine with a `pseudo(the_species)%chpcc%f` lookup and again causes a segfault when using the Cray Fortran compiler.

The segfault with Cray Fortran can be avoided by entirely disabling scalar optimisations, but the `j` and `j+1` indices being used with the table lookups will still be incorrect.

To fix the issue, lines 3650 and 3815 in force_module.f90 should be changed from

```fortran
rsq = rx * rx + ry * ry + rz * rz
```

to

```fortran
rsq = r(1) * r(1) + r(2) * r(2) + r(3) * r(3)
```

**Comment by davidbowler** [comment]
Fixed with #86
