### ISSUE TITLE
Error Basis Generation with Hf

### ISSUE THREAD

**Issue by negf** [OrderN/CONQUEST-release#87]
I tried to generate ion file for Hf using the pot file and input supplied with Conquest. I get the following error from MakeIonFiles

  Solving for PAOs
 Rc and rr(nmax) are:    8.28664387002489        8.28664387002489
  Error in process    1
  ERROR in perturbative polarisation routines - prefactor not found
  Error in process    1
  ERROR in perturbative polarisation routines - prefactor not found

I am on "Git Branch: develop; tag, hash: v1.0.5-pre-56-ge241672e".

**Comment by davidbowler** [comment]
This is not so much a bug as a technical issue with the generation of polarisation orbitals.  Please add the line:

Atom.Perturbative_Polarised F

into the %block Hf atom block.  This will generate basis functions without error, but please test them carefully.

**Comment by negf** [comment]
Ok thanks. This is what I did. I was just puzzled as it was working with previous versions.

--------------------------------------------------------------------------------------------------------
マリウス　ビュクル, Ph.D.

bI技gt合研究所
C能材料コンピュテ`ショナルデザイン研究センタ`　
305-8568 茨城hつくば市梅@ 1-1-1 つくば中央第2

TEL: 029-862-6947
FAX: 029-861-3171
E-mail: ***@***.***


Marius Buerkle, Ph.D.

Research Center for Computational Design of Advanced Functional Materials, AIST

Central2, 1-1-1, Umezono, Tsukuba, 305-8568, Japan

TEL: 029-862-6947
FAX: 029-861-3171
E-mail: ***@***.***

--------------------------------------------------------------------------------------------------------
________________________________

**Comment by davidbowler** [comment]
That's interesting! Can you give a version number that you know worked? And (if possible) can you test the two basis sets, to see what change there might be?

**Comment by negf** [comment]
For  "Atom.Perturbative_Polarised t", it works for the current master (commit 087c2a6cb50eca80127a5a194cd710f0777472d0 (HEAD, tag: v1.0.6-pre, origin/master, origin/HEAD, master)) but fails for the current develop branch (commit e241672e91f3549e16fa835090459e4884627fbe).

For  "Atom.Perturbative_Polarised f" the master and develop version give identical results.

--------------------------------------------------------------------------------------------------------
マリウス　ビュクル, Ph.D.

bI技gt合研究所
C能材料コンピュテ`ショナルデザイン研究センタ`　
305-8568 茨城hつくば市梅@ 1-1-1 つくば中央第2

TEL: 029-862-6947
FAX: 029-861-3171
E-mail: ***@***.***


Marius Buerkle, Ph.D.

Research Center for Computational Design of Advanced Functional Materials, AIST

Central2, 1-1-1, Umezono, Tsukuba, 305-8568, Japan

TEL: 029-862-6947
FAX: 029-861-3171
E-mail: ***@***.***

--------------------------------------------------------------------------------------------------------
________________________________

**Comment by davidbowler** [comment]
This problem is also found for other transition metals (Ti, Zr among others) and Pd (see issue #93).

It turns out that the master version (and earlier develop versions) are actually buggy, and shouldn't work.  A bug fix is coming soon.

**Comment by davidbowler** [comment]
Fixed with #97
