### ISSUE TITLE
Compilation error with fft_module.f90

### ISSUE THREAD

**Issue by alexmsilva20** [OrderN/CONQUEST-release#88]
Hi everyone,

I was trying to compile Conquest code with mpif90, Blas, Lapack and Scalapack from MKL intel. For FFT libs, I have chosen the 
FFT_LIBS="-lmkl_intel_lp64 -lmkl_sequential -lmkl_core", as used for another compilations of quantum mechanics codes. After make command, the compilations fails at fft_module.f90 in the line
use fft_interface_module with following error mesage:
"error #7002: error in opening the compiled module file. check include paths"
I do not know how to solve that. A similar problem occurs with the ol_bessel.f90 file with the same line use fft_interface_module.
Using a libfftw3.a library, built after fftw3 compilation, the problem persists. 
Anyone have an idea hwo to solve this compilation error?

Thanks

**Comment by davidbowler** [comment]
Hi Alex.  This isn't an issue with Conquest, but with specifying the FFTW location.  In general, as compilation is system-dependent, we can't offer any help, and you should talk to your system administrator.

In this case, you shouldn't be giving the MKL libraries in FFT_LIB but in BLAS.  Please also check that you have set FFT_OBJ correctly (as in the supplied system.make file):

# Set FFT library
FFT_LIB=-lfftw3
FFT_OBJ=fft_fftw3.o

**Comment by alexmsilva20** [comment]
Thank you


Em sex., 16 de abr. de 2021 às 04:32, David Bowler ***@***.***>
escreveu:
