### ISSUE TITLE
Can't find a good block size: please set manually

### ISSUE THREAD

**Issue by alexmsilva20** [OrderN/CONQUEST-release#89]
Hi everyone,

I have just successfully compiled Conquest code with icc/ifort/mpicc/mpifort/blas+lapack+scalapack from MKL/FFTw3. I have successfully started a serial job in the head node of my cluster. However, when I have tried run the same Conquest_input by means a PBS script with parallel execution, I have got the following error message:
Error in process    1
Can't find a good block size: please set manually
...
Error in process    48
Can't find a good block size: please set manually

The execution line of PBS script is:
mpirun -np 48  /home/users/amartins/src/CONQUEST-release-master/bin/Conquest < Conquest_input > Conquest_out

What's happened? Does anyone have an idea how to fix this?

Thanks in advance.

**Comment by davidbowler** [comment]
This isn't an issue (i.e. a bug with Conquest) so the issues area is the wrong place to be posting these queries.

Please use the Conquest mailing list (see "Getting in touch" under the manual page: https://conquest.readthedocs.io/en/latest/index.html) for these queries on running the code

**Comment by alexmsilva20** [comment]
Hi David,

I'm so sorry. I  don't see this information on the first page (menu) of
online manual.

Em seg., 19 de abr. de 2021 às 05:01, David Bowler ***@***.***>
escreveu:
