### ISSUE TITLE
Requirement of vecLibFort

### ISSUE THREAD

**Issue by 1314DA** [OrderN/CONQUEST-release#96]
The CONQUEST `system.make` requires the `vecLibFort` library to compile. As far as I know, this is only available if you have Mac OS X. At least the source code of vecLibFort (i.e. `vecLibFort.c`) requires the `Accelerate.h` which, in turn, is exclusive to Apple systems.

Am I correct, that this prevents me from compiling the software on, say, a Linux cluster?
I already tried compiling without `vecLibFort` but the compile crashes. In that case a kind of namespace error appears, due to the trailing underscore of external routines in e.g. `LAPACK` that are not present in the CONQUEST source code.
(e.g. `generic_blas.o: undefined reference to symbol 'dpotri_'`) 
I guess that this is exactly what `vecLibFort` is good for...

Any help will be appreciated. Maybe I'm just unaware of some obvious work-around for this problem.

**Comment by tsuyoshi38** [comment]
CONQUEST needs BLAS, LAPACK, SCALAPACK for the Math Library, (we also need MPI, FFTW and preferably libXC), and you need to modify `system.make` for your compiler and OS.

As you said, `vecLibFort` is the library for MacOS X.  
It should be also possible to install these libraries by yourself, but I think you can find the library (like MKL) for your compiler and OS.

**Comment by 1314DA** [comment]
Thank you for the quick reply.

My mistake was to use the `master` branch of the release version.
Once I tried the `develop` branch and set the libraries correctly, everything worked seamlessly. 
Documentation in the `system.make` has much improved in the `develop` branch!
